/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newbiz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kasun
 */
public class customer_payment_summery1 extends javax.swing.JFrame {

    /**
     * Creates new form Supplier_payment_summery
     */
    public customer_payment_summery1() {
        initComponents();
        load_sup();
        valueset();
        load_data();
    }
void valueset(){
jTextField2.setText("0.0");
jTextField3.setText("0.0");
}
    void load_data(){
    
        try {
            Connection com = DB.conect();
            ResultSet r = com.createStatement().executeQuery("select * from customer where fname='" + jComboBox1.getSelectedItem() + "'");
            String cusid = null;
            while (r.next()) {
                cusid = r.getString("cusid");
            }
            
            
            ResultSet p = com.createStatement().executeQuery("select * from customerpaymentsummery where cusid='" + cusid + "'");
            int totalCredit = 0;
            while (p.next()) {
               
            
               totalCredit=totalCredit+Integer.parseInt(p.getString("balance"));
          
            }
            
            jTextField1.setText(totalCredit+"");
        } catch (Exception ex) {
            Logger.getLogger(customer_payment_summery1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    void load_table() {
        try {

            Connection com = DB.conect();
            ResultSet r = com.createStatement().executeQuery("select * from customer where fname='" + jComboBox1.getSelectedItem() + "'");
            String cusid = null;
            while (r.next()) {
                cusid = r.getString("cusid");
            }
            System.out.println(cusid);
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int i = dtm.getRowCount();
            while (i > 0) {
                dtm.removeRow(i - 1);
                i--;

            }

            ResultSet p = com.createStatement().executeQuery("select * from customerpaymentsummery where cusid='" + cusid + "'");

            while (p.next()) {
                Vector v = new Vector();
                v.add(p.getString("invoNo"));
                v.add(p.getString("invotot"));
                v.add(p.getString("cash"));
                v.add(p.getString("cheque"));
                v.add(p.getString("balance"));
                v.add(p.getString("paydate"));

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void load_sup() {
        try {
            Connection com = DB.conect();
            ResultSet q = com.createStatement().executeQuery("select fname from customer");
            while (q.next()) {
                String sup = q.getString("fname");
                jComboBox1.addItem(sup);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Customer Payment Summery");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 381, 37));

        jLabel2.setText("Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 69, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select  a customer" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 87, -1));

        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));
        getContentPane().add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN NO", "Total", "Cash", "Cheque", "Balence", "Last Payment"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 136, 640, 270));

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        jLabel4.setText("Credit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel5.setText("cash");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        jLabel6.setText("Discount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        jLabel7.setText("Balance");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 70, 20));

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 70, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 70, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 70, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        load_table();
 load_data();         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            Object ob=dtm.getValueAt(jTable1.getSelectedRow(),4);
            jTextField4.setText(ob+"");
            jTextField1.setText(ob+"");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
    try {
            String cash = jTextField2.getText().trim();

            String cheque = jTextField3.getText().trim();
            if (cash == "" || cash.equals("")) {
                cash = "0.0";

            }
            if (cheque == "" || cheque.equals("")) {
                cheque = "0.0";

            }
            double credit = Double.parseDouble(jTextField1.getText());
            double balance = credit - (Double.parseDouble(cash) + Double.parseDouble(cheque));
            jTextField4.setText(balance + "");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
  try {
            String cash = jTextField2.getText().trim();

            String cheque = jTextField3.getText().trim();
            if (cash == "" || cash.equals("")) {
                cash = "0.0";

            }
            if (cheque == "" || cheque.equals("")) {
                cheque = "0.0";

            }
            double credit = Double.parseDouble(jTextField1.getText());
            double balance = credit - (Double.parseDouble(cash) + Double.parseDouble(cheque));
            jTextField4.setText(balance + "");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {
            String d = dateChooserCombo1.getText();
            String date[] = d.split("/");
            String realdate = date[2] + "-" + date[0] + "-" + date[1];

            Connection com = DB.conect();
            ResultSet r = com.createStatement().executeQuery("select * from customer where fname='" + jComboBox1.getSelectedItem() + "'");
            String cusid = null;
            while (r.next()) {
                cusid = r.getString("cusid");
            }
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Object ob1= dtm.getValueAt(jTable1.getSelectedRow(),0 );
          Object ob2= dtm.getValueAt(jTable1.getSelectedRow(),1 );
           Object ob3= dtm.getValueAt(jTable1.getSelectedRow(),2 ); 
            
            
            double cash= Double.parseDouble(jTextField2.getText());
            
            double newcash=cash+Double.parseDouble(ob3.toString());
            
            System.out.println(newcash);
          
            
            
            
              PreparedStatement k2 = com.prepareStatement("insert into customerpayment values('" + cusid + "','" + ob1 + "','" + ob2 + "','" + ob3 + "','" + jTextField4.getText() + "','" + jTextField3.getText() + "','" + realdate + "')");
            k2.executeUpdate();            
            k2.close();
            PreparedStatement k1 = com.prepareStatement("update customerpaymentsummery set cash='" + ob3 + "',cheque='" + jTextField3.getText() + "',cheque='" + jTextField4.getText() + "'where cus_id='" + cusid + "'");
            k1.executeUpdate();            
            k1.close();
            
            load_table();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_payment_summery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_payment_summery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_payment_summery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_payment_summery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_payment_summery1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
