/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package newbiz;

import com.sun.org.apache.xml.internal.dtm.DTM;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class SupplierPayments extends javax.swing.JFrame {

    /**
     * Creates new form SupplierPayments
     */
    public SupplierPayments() {
        initComponents();
        loadsuplier();
        loadtable();
    }

    void catot() {
        try {
            String cash = jTextField9.getText();
            String cheq = jTextField10.getText();
            if (cash.isEmpty()) {
                cash = "0";
            }
            if (cheq.isEmpty()) {
                cheq = "0";
            }
            jTextField11.setText(Double.parseDouble(jTextField8.getText()) - (Double.parseDouble(cash) + Double.parseDouble(cheq)) + "");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadsuplier() {
        try {
            Connection com = DB.conect();
            ResultSet r = com.createStatement().executeQuery("select * from supplier");
            while (r.next()) {
                jComboBox1.addItem(r.getString("fname"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadtable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int rowcount = dtm.getRowCount();
            while (rowcount > 0) {
                dtm.removeRow(rowcount - 1);
                rowcount--;
            }

            Connection com = DB.conect();

            ResultSet r = com.createStatement().executeQuery("select supid from supplier where fname='" + jComboBox1.getSelectedItem() + "'");
            String sid = null;
            while (r.next()) {
                sid = r.getString("supid");
            }
            ResultSet r1 = com.createStatement().executeQuery("select * from supplierpaymentsummery where supid='" + sid + "'");
            while (r1.next()) {
                Vector v = new Vector();
                v.add(r1.getString("grnNo"));
                v.add(r1.getString("grntot"));
                v.add(r1.getString("cash"));
                v.add(r1.getString("cheque"));
                v.add(r1.getString("balance"));
                v.add(r1.getString("grndate"));
                v.add(r1.getString("paydate"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN No", "GRN Total", "Total Cash", "Total Cheque", "Balance", "GRN Date", "Last Pay Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 82, 690, 174));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Total  Credit");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 274, -1, -1));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setText("0.0");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 274, 146, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Cash");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 303, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setText("0.0");
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField9MouseExited(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 303, 146, 24));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Cheque");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 340, -1, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.setText("0.0");
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField10MouseExited(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 333, 144, 24));

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.setText("0.0");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 362, 146, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Balance");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 365, -1, -1));

        jButton8.setText("Insert Info");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 339, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...Select A Supplier..." }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 38, 161, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Supplier Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 35, 100, 29));

        jButton10.setText("Delete A Row");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 30));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setText("PAY");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 278, 244, 64));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText(" Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 38, -1, -1));

        dateChooserCombo2.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));
        jPanel1.add(dateChooserCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 35, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(732, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            jTextField10.setText("0.0");
            jTextField11.setText("0.0");
            jTextField8.setText("0.0");
            jTextField9.setText("0.0");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            Object ob = dtm.getValueAt(jTable1.getSelectedRow(), 4);
            Object ob1 = dtm.getValueAt(jTable1.getSelectedRow(), 2);
            Object ob2 = dtm.getValueAt(jTable1.getSelectedRow(), 3);
//            Object ob1[] = new Object[6];
//            int i = dtm.getRowCount();
//            for (int a = 0; a < i; a++) {
//                for (int b = 0; b < 6; b++) {
//                    ob1[b] = dtm.getValueAt(a, b);
//                }
            jTextField8.setText(ob + "");
            jTextField11.setText(ob + "");

//            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseEntered
        if (jTextField9.getText().equals("0.0")) {
            jTextField9.setText("");
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9MouseEntered

    private void jTextField9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseExited
        if (jTextField9.getText().isEmpty()) {
            jTextField9.setText("0.0");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9MouseExited

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        catot();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseEntered
        if (jTextField10.getText().equals("0.0")) {
            jTextField10.setText("");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10MouseEntered

    private void jTextField10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseExited
        if (jTextField10.getText().isEmpty()) {
            jTextField10.setText("0.0");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10MouseExited

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        catot();         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            Connection com = DB.conect();
            String d1 = dateChooserCombo2.getText();
            String d2[] = d1.split("/");
            String realDate = d2[2] + "-" + d2[0] + "-" + d2[1];
            ResultSet r = com.createStatement().executeQuery("select supid from supplier where fname='" + jComboBox1.getSelectedItem() + "'");
            String sid = null;
            while (r.next()) {
                sid = r.getString("supid");
            }
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            Object ob0 = dtm.getValueAt(jTable1.getSelectedRow(), 0);//tot
            Object ob = dtm.getValueAt(jTable1.getSelectedRow(), 4);//tot
            Object ob1 = dtm.getValueAt(jTable1.getSelectedRow(), 2);//cash
            Object ob2 = dtm.getValueAt(jTable1.getSelectedRow(), 3);//cheque
           Object ob3 = dtm.getValueAt(jTable1.getSelectedRow(), 5);//cheque
//       
            PreparedStatement p1 = com.prepareStatement("insert into supplierpayment values('" + sid + "','" + ob0 + "','" + ob + "','" + jTextField9.getText() + "','" + jTextField10.getText() + "','" + jTextField11.getText() + "','" + ob3 + "','" + realDate + "')");
            p1.executeUpdate();
            p1.close();
            double newCash = Double.parseDouble(ob1.toString()) + Double.parseDouble(jTextField9.getText());
            double newCheque = Double.parseDouble(ob2.toString()) + Double.parseDouble(jTextField10.getText());

//            }
            PreparedStatement p = com.prepareStatement("update supplierpaymentsummery set cash='" + newCash + "',cheque='" + newCheque + "',balance='" + jTextField11.getText() + "',paydate='" + realDate + "'where supid='" + sid + "' and grnNo='" + ob0 + "' and grndate='"+ob3+"'");
            p.executeUpdate();
            p.close();
            loadtable();

            jTextField10.setText("0.0");
            jTextField11.setText("0.0");
            jTextField8.setText("0.0");
            jTextField9.setText("0.0");
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        loadtable();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.removeRow(jTable1.getSelectedRow());      // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierPayments().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
